# Base configuration template for all GAN models
experiment:
  name: base_experiment
  seed: 42
  output_dir: ./outputs
  log_interval: 100
  save_interval: 1000
  num_epochs: 100
  num_workers: 4
  device: cuda

data:
  name: mnist  # Options: mnist, fashion_mnist, cifar10, celeba, celeba_hq, ffhq
  batch_size: 64
  image_size: 28  # Initial size for the dataset
  channels: 1

model:
  name: base_gan
  latent_dim: 100
  hidden_dim: 128

training:
  optimizer: adam
  lr_g: 0.0002
  lr_d: 0.0002
  beta1: 0.5
  beta2: 0.999
  use_scheduler: false
  scheduler_gamma: 0.99
  n_critic: 1  # Number of discriminator updates per generator update

logging:
  use_tensorboard: true
  use_wandb: false
  wandb_project: gans-research