# Configuration for Conditional GAN on MNIST
experiment:
  name: cgan_mnist
  seed: 42
  output_dir: ./outputs/cgan
  log_interval: 100
  save_interval: 1000
  num_epochs: 50
  num_workers: 4
  device: cuda

data:
  name: mnist
  batch_size: 100
  image_size: 28
  channels: 1
  num_classes: 10 # Number of class labels for conditioning

model:
  name: cgan
  latent_dim: 100
  hidden_dim_z: 200
  hidden_dim_y: 1000
  combined_hidden_dim: 1200
  embedding_dim: 10 # Dimension of condition embedding
  use_batch_norm: true
  use_dropout: true
  dropout_prob: 0.5

training:
  optimizer: adam
  lr_g: 0.0002
  lr_d: 0.0002
  beta1: 0.5
  beta2: 0.999
  use_scheduler: true
  scheduler_type: exponential
  scheduler_gamma: 0.99996
  n_critic: 1

evaluation:
  use_fid: false
  batch_size: 100
  num_samples: 1000
  eval_epoch_interval: 1

logging:
  use_tensorboard: false
  use_wandb: true
  wandb_project: gans-research
