# Progressive Growing GAN (ProGAN) config
experiment:
  name: prog_gan_mnist
  seed: 42
  output_dir: ./outputs/prog_gan
  log_interval: 200
  sampling_num: 16
  save_interval: 1000
  num_epochs: 80
  device: cuda

data:
  name: mnist          
  channels: 1           
  image_size: 512      
  batch_sizes:
    4: 128
    8: 64
    16: 64
    32: 32
    64: 32
    128: 16

model:
  name: prog_gan
  latent_dim: 512
  feature_maps: 8192      
  fmap_decay: 1.0         
  fmap_max: 512           
  starting_resolution: 4 

training:
  optimizer: adam
  lr_g: 0.001
  lr_d: 0.001
  beta1: 0.0
  beta2: 0.99
  epsilon: 1e-8
  epsilon_drift: 0.001     
  n_critic: 1               
  lambda_gp: 10.0

progressive:
  resolutions: [4, 8, 16, 32, 64, 128, 256, 512]  
  fadein_kimgs: 600000
  images_per_stage: 600000

evaluation:
  use_fid: false
  batch_size: 64
  num_samples: 100
  eval_epoch_interval: 1

inference:
  checkpoint_path: ./outputs/prog_gan/checkpoints/final_model.pth
  num_samples: 16

logging:
  use_tensorboard: false
  use_wandb: true
  wandb_project: gans-research
